# CodeRabbit 설정 파일 - Java 프로젝트용
language: "ko-KR"
tone_instructions: "한국어로 친근하고 건설적인 피드백을 제공해주세요."

reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords: ["wip", "draft"]

  # 경로별 코드 컨벤션 검사 규칙
  path_instructions:
    - path: "**/*.java"
      instructions: |
        CODING_STANDARDS.md 파일에 명시된 코드 컨벤션을 준수하여 리뷰해주세요.
        특히 다음 사항들을 중점적으로 확인해주세요:
        - Javadoc 작성 규칙
        - 테스트 코드 작성 전략
        - DTO, Entity, Controller 구현 방식
        - 정적 팩토리 메서드 사용법
        - 버전 관리 및 네이밍 컨벤션

  # 필터링 - 불필요한 파일 제외
  path_filters:
    - "!**/target/**"
    - "!**/build/**"
    - "!**/.gradle/**"
    - "!**/node_modules/**"
    - "src/**/*.java"
    - "test/**/*.java"

  # 도구 설정
  tools:
    # Java 관련 도구들
    pmd:
      enabled: true
    checkstyle:
      enabled: true
    spotbugs:
      enabled: true
    
    # 보안 검사
    gitleaks:
      enabled: true
    semgrep:
      enabled: true

# 코드 생성 설정
code_generation:
  docstrings:
    language: "ko"
    path_instructions:
      - path: "**/*.java"
        instructions: "CODING_STANDARDS.md 파일의 Javadoc 규칙에 따라 문서 주석을 생성해주세요."
          
  unit_tests:
    path_instructions:
      - path: "**/*.java"
        instructions: "CODING_STANDARDS.md 파일의 테스트 코드 규칙에 따라 각 계층에 맞는 단위 테스트를 생성해주세요."

# 지식 베이스 설정
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CODING_STANDARDS.md"
      - "**/README.md"
      - "**/.cursorrules"

chat:
  auto_reply: true
  art: true