# CodeRabbit 설정 파일 - Java 프로젝트용
language: "ko-KR"
tone_instructions: "한국어로 친근하고 건설적인 피드백을 제공해주세요."

reviews:
  # assertive를 concise로 변경하여 간결한 리뷰를 요청
  profile: "concise" 
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords: ["wip", "draft"]

  # path_instructions 섹션을 삭제하거나 중요한 내용만 남겨 불필요한 리뷰를 줄임
  # 이 예시에서는 삭제함
  path_instructions:
    - path: "**/*.java"
      instructions: |
        코드의 잠재적인 버그, 보안 취약점, 또는 심각한 성능 문제에 대해서만 중점적으로 리뷰해주세요.
        코드 컨벤션에 대한 자세한 피드백은 피해주세요.

  # 필터링 - 불필요한 파일 제외
  path_filters:
    - "!**/target/**"
    - "!**/build/**"
    - "!**/.gradle/**"
    - "!**/node_modules/**"
    - "src/**/*.java"
    - "test/**/*.java"

  # 도구 설정 - 세부적인 코딩 스타일 검사 도구 비활성화
  tools:
    pmd:
      enabled: false
    checkstyle:
      enabled: false
    spotbugs:
      enabled: true
    gitleaks:
      enabled: true
    semgrep:
      enabled: true

# 코드 생성 설정 (기존과 동일하게 유지)
code_generation:
  docstrings:
    language: "ko"
    path_instructions:
      - path: "**/*.java"
        instructions: "CODING_STANDARDS.md 파일의 Javadoc 규칙에 따라 문서 주석을 생성해주세요."
  unit_tests:
    path_instructions:
      - path: "**/*.java"
        instructions: "CODING_STANDARDS.md 파일의 테스트 코드 규칙에 따라 각 계층에 맞는 단위 테스트를 생성해주세요."

# 지식 베이스 설정 (기존과 동일하게 유지)
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CODING_STANDARDS.md"
      - "**/README.md"
      - "**/.cursorrules"

chat:
  auto_reply: true
  art: true
