spring:
  config:
    import:
      optional:file:.env[.properties]
  application:
    name: moyeohaeng
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        use_sql_comments: true
        highlight_sql: true
    show-sql: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    expire-length: ${JWT_ACCESS_TOKEN_EXPIRE_LENGTH:3600000} # 1시간
  refresh-token:
    expire-length: ${JWT_REFRESH_TOKEN_EXPIRE_LENGTH:604800000} # 7일

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept,Origin,X-Requested-With}

logging:
  level:
    eightbit.moyeohaeng: ${LOGGING_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_SQL_PARAMS:TRACE}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}

server:
  port: ${SERVER_PORT:8080}
