spring:
  application:
    name: moyeohaeng
  datasource:
    url: ${SPRING_MYSQL_URL}
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
    show-sql: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

sse:
  cache:
    limit: ${SSE_CACHE_LIMIT:100}
    ttl: ${SSE_CACHE_TTL:30m}
  scheduling:
    heartbeat:
      fixed-rate: ${SCHEDULING_FIXED_RATE:30000}

jwt:
  secret:
    key: ${SPRING_JWT_SECRET_KEY}
  access-token:
    expire-length: 3600000 # 1시간
  refresh-token:
    expire-length: 604800000 # 7일

cors:
  allowed-origins: https://moyeohaeng.online,https://dev.moyeohaeng.online
  allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
  allowed-headers: Content-type,Authorization

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    enabled: false

server:
  port: 8080
